import { auth } from "./auth.js";
import { showToast } from "./ui.js";
import { navigate } from "./router.js";
import { googleIdentity } from "./google-identity.js";
import { installState, requestInstall } from "./install.js";

let loginController=null, loginHydrationId=0;
const moduleCache=new Map();
function setText(id,value){const el=document.getElementById(id);if(el)el.textContent=String(value??"");}
function clean(value){return String(value??"").replace(/[\u0000-\u001F\u007F]/g," ").replace(/\s+/g," ").trim();}
function publicConfig(){return auth.current().backend?.publicConfig||{};}
async function feature(path,exportName){let p=moduleCache.get(path);if(!p){p=import(path);moduleCache.set(path,p);}const m=await p;if(typeof m[exportName]!=="function")throw new Error(`Modul ${exportName} fehlt.`);return m[exportName]();}
async function hydrateHome(){if(auth.isAuthenticated()){navigate(auth.requiresProfile()?"profile":"dashboard");return;}const cfg=publicConfig();setText("publicHeadline",cfg.headline||"Herzlich willkommen bei den Schweinfurter Plärrdeifln");setText("publicConstructionText",cfg.note||"Das Plärrdeifl Portal befindet sich noch im Aufbau.");}
async function simple(id,key,fallback){setText(id,publicConfig()[key]||fallback);}
async function hydrateInstall(){const button=document.getElementById("pageInstallButton"),instructions=document.getElementById("installInstructions"),result=document.getElementById("installResult");const render=()=>{const s=installState();if(!instructions||!button)return;if(s.standalone){instructions.textContent="Das Portal ist bereits als App geöffnet.";button.hidden=true;return;}button.hidden=false;if(s.ios){instructions.innerHTML="<ol><li>In Safari öffnen.</li><li>Teilen wählen.</li><li>Zum Home-Bildschirm wählen.</li><li>Hinzufügen bestätigen.</li></ol>";button.textContent="Anleitung anzeigen";}else if(s.promptAvailable){instructions.textContent="Dein Browser kann das Portal direkt als App installieren.";button.textContent="Portal installieren";}else{instructions.innerHTML="<p>Öffne das Browsermenü und wähle <strong>App installieren</strong> oder <strong>Zum Startbildschirm hinzufügen</strong>.</p>";button.textContent="Installationshinweis";}};button?.addEventListener("click",async()=>{const s=installState();if(s.ios||!s.promptAvailable){result.textContent=s.ios?"Safari → Teilen → Zum Home-Bildschirm.":"Nutze den Installationsbefehl im Browsermenü.";return;}const out=await requestInstall();result.textContent=out.installed?"Das Portal wurde installiert.":"Installation wurde nicht abgeschlossen.";render();});render();}
function registrationForm(registration){const slot=document.getElementById("registrationSlot");if(!slot||!registration)return;const p=registration.profile||{};slot.hidden=false;slot.innerHTML=`<div class="notice warning"><strong>Freischaltungsantrag vervollständigen</strong><br>Google hat kein bereits freigeschaltetes Benutzerkonto gefunden. Beide Namensfelder sind Pflichtfelder.</div><form id="registrationForm" class="form-grid" novalidate><label>Vorname *<input name="vorname" autocomplete="given-name" required maxlength="160" value="${escapeAttr(p.vorname||"")}" aria-describedby="registrationFirstError"><small id="registrationFirstError" class="field-error"></small></label><label>Nachname *<input name="nachname" autocomplete="family-name" required maxlength="160" value="${escapeAttr(p.nachname||"")}" aria-describedby="registrationLastError"><small id="registrationLastError" class="field-error"></small></label><div class="full dialog-actions"><button class="button primary" type="submit">Freischaltungsantrag senden</button></div></form>`;slot.querySelector("form")?.addEventListener("submit",async event=>{event.preventDefault();const data=Object.fromEntries(new FormData(event.currentTarget));data.vorname=clean(data.vorname);data.nachname=clean(data.nachname);document.getElementById("registrationFirstError").textContent=data.vorname?"":"Vorname fehlt.";document.getElementById("registrationLastError").textContent=data.nachname?"":"Nachname fehlt.";if(!data.vorname||!data.nachname)return;const b=event.currentTarget.querySelector('button[type="submit"]');b.disabled=true;b.textContent="Wird gesendet …";try{await auth.submitAccessRequest(data);slot.innerHTML='<div class="notice success"><strong>Antrag gespeichert.</strong><br>Nach der Freigabe kannst du dich erneut mit Google anmelden.</div>';showToast("Freischaltungsantrag gespeichert.","success",5200);}catch(e){showToast(e.message||"Antrag konnte nicht gespeichert werden.","error",6500);b.disabled=false;b.textContent="Freischaltungsantrag senden";}});}
function escapeAttr(v){return String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));}
async function hydrateLogin(){const id=++loginHydrationId;googleIdentity.destroyButton();loginController=null;const current=auth.current(),retry=document.getElementById("loginRetryButton"),notice=document.getElementById("loginNotice"),pill=document.getElementById("loginStatusPill"),slot=document.getElementById("googleSignInButton");setText("bridgeStatusText",current.backend?`Verbunden · ${current.backend.version||current.backend.build||"Backend bereit"}`:"Backend nicht erreichbar.");setText("oauthStatusText",current.backend?.gisConfigured?"Direkter Google-Popup-Login ist bereit.":"Google Client-ID fehlt oder ist ungültig.");if(current.registration){registrationForm(current.registration);if(pill){pill.textContent="Angaben erforderlich";pill.className="status-pill warning";}setText("loginMessage","Vervollständige Vorname und Nachname.");return;}if(current.authenticated){if(pill){pill.textContent=current.profileRequired?"Profil unvollständig":"Angemeldet";pill.className=`status-pill ${current.profileRequired?"warning":"success"}`;}setText("loginMessage",current.profileRequired?"Vorname und Nachname müssen ergänzt werden.":`Du bist als ${current.user?.name||"Portaluser"} angemeldet.`);slot.innerHTML=`<button id="loginHomeButton" class="button primary" type="button">${current.profileRequired?"Profil vervollständigen":"Zum Dashboard"}</button>`;document.getElementById("loginHomeButton")?.addEventListener("click",()=>navigate(current.profileRequired?"profile":"dashboard"));return;}if(!current.backend?.gisConfigured||!current.backend?.googleClientId){setText("loginMessage","Direkter Google-Login ist noch nicht vollständig konfiguriert.");return;}const mount=async()=>{if(id!==loginHydrationId)return;if(retry)retry.disabled=true;setText("loginMessage","Google-Anmeldung wird sicher vorbereitet …");try{loginController=await googleIdentity.renderButton(slot,{clientId:current.backend.googleClientId,onCredential:async({credential,nonce})=>{const result=await auth.signInWithGoogleCredential(credential,nonce);if(result.authenticated){googleIdentity.destroyButton();navigate(result.profileRequired?"profile":"dashboard");return{refresh:false};}if(result.registration){registrationForm(result.registration);return{refresh:false};}return{refresh:true};},onError:async e=>{showToast(e.message||"Google-Anmeldung fehlgeschlagen.","error",6500);}});if(pill){pill.textContent="Bereit";pill.className="status-pill success";}setText("loginMessage","Wähle dein Google-Konto aus.");}finally{if(retry)retry.disabled=false;}};retry?.addEventListener("click",mount);await mount();}
export async function hydratePage(key){if(key!=="login"){loginHydrationId++;googleIdentity.destroyButton();loginController=null;}if(key==="home")return hydrateHome();if(key==="news")return simple("publicNewsText","news","Neuigkeiten werden hier veröffentlicht.");if(key==="dates")return simple("publicDatesText","dates","Kommende Termine werden hier angekündigt.");if(key==="about")return simple("publicAboutText","about","Hier entsteht die Vorstellung der Schweinfurter Plärrdeifl.");if(key==="contact")return simple("publicContactText","contact","Kontaktinformationen werden hier veröffentlicht.");if(key==="install")return hydrateInstall();if(key==="login")return hydrateLogin();if(key==="profile")return feature("./modules/profile.js","hydrateProfile");if(key==="dashboard")return feature("./modules/dashboard.js","hydrateDashboard");if(key==="fanclub")return feature("./modules/fanclub.js","hydrateFanclub");if(key==="tasks")return feature("./modules/tasks.js","hydrateTasks");if(key==="teams")return feature("./modules/teams.js","hydrateTeams");if(key==="fanbuses")return feature("./modules/fanbuses.js","hydrateFanbuses");if(key==="admin")return feature("./modules/admin.js?v=20260714-r71-m4-1","hydrateAdmin");}
