import { CONFIG } from "./config.js";
import { auth } from "./auth.js";
import { currentRoute, fixedAuthenticatedOrder, navigate, routes } from "./router.js";
export async function loadFragment(path,{signal}={}){
  const response=await fetch(path,{cache:"no-store",signal});
  if(!response.ok)throw new Error(`Datei konnte nicht geladen werden: ${path}`);
  return response.text();
}
export async function mountComponents(){const [s,t]=await Promise.all([loadFragment("./components/sidebar.html"),loadFragment("./components/topbar.html")]);document.getElementById("sidebarSlot").innerHTML=s;document.getElementById("topbarSlot").innerHTML=t;}
export function visibleRouteEntries(){if(!auth.isAuthenticated())return Object.entries(routes()).filter(([,r])=>r.public).sort((a,b)=>(a[1].publicOrder||0)-(b[1].publicOrder||0));if(auth.requiresProfile())return [["profile",routes().profile]];return fixedAuthenticatedOrder().filter(k=>auth.canAccessRoute(k)).map(k=>[k,routes()[k]]);}
export function renderNavigation(){const nav=document.getElementById("mainNav");if(!nav)return;nav.replaceChildren(...visibleRouteEntries().map(([key,route])=>{const b=document.createElement("button");b.type="button";b.dataset.route=key;const icon=document.createElement("span");icon.className="nav-icon";icon.setAttribute("aria-hidden","true");icon.textContent=route.icon;const label=document.createElement("span");label.textContent=route.title;b.append(icon,label);return b;}));updateActiveNavigation();}
export function updateActiveNavigation(){const active=currentRoute();document.querySelectorAll("#mainNav [data-route]").forEach(e=>e.classList.toggle("active",e.dataset.route===active));}
export function updateUserChrome(){const c=auth.current(),summary=document.getElementById("userSummary"),logout=document.getElementById("logoutButton");if(summary)summary.hidden=!c.authenticated;if(logout)logout.hidden=!c.authenticated;if(c.authenticated&&c.user){const first=c.user.firstName||c.user.vorname||"",last=c.user.lastName||c.user.nachname||"";const name=(first+" "+last).trim()||c.user.name||"Profil unvollständig";document.getElementById("userSummaryName").textContent=name;document.getElementById("userSummaryRole").textContent=c.profileRequired?"Profilvervollständigung erforderlich":(c.user.role||"Portaluser");}}
export function bindGlobalUi({onRefresh,onLogout}={}){document.addEventListener("click",e=>{const target=e.target.closest("[data-route]");if(target){e.preventDefault();const p=new URLSearchParams();if(target.dataset.openTab)p.set("tab",target.dataset.openTab);navigate(target.dataset.route,p);closeMobileMenu();return;}if(e.target.closest("[data-close-menu]"))closeMobileMenu();});document.getElementById("mobileMenuToggle")?.addEventListener("click",openMobileMenu);document.getElementById("refreshButton")?.addEventListener("click",()=>onRefresh?.());document.getElementById("logoutButton")?.addEventListener("click",()=>onLogout?.());document.getElementById("buildLabel").textContent=`${CONFIG.app.version} · ${CONFIG.app.build}`;}
export function setRouteHeader(route){const title=document.getElementById("routeTitle"),subtitle=document.getElementById("routeSubtitle");if(title)title.textContent=route.title;if(subtitle)subtitle.textContent=route.subtitle;document.title=`${route.title} · ${CONFIG.app.name}`;}
export function showToast(message,type="info",duration=3200){const region=document.getElementById("toastRegion");if(!region)return;const toast=document.createElement("div");toast.className=`toast ${type}`;toast.textContent=message;region.appendChild(toast);setTimeout(()=>toast.remove(),duration);}
export function setConnectionStatus(label,type="success"){const s=document.getElementById("connectionStatus");if(s){s.textContent=label;s.className=`status-pill ${type}`;}}
export function openMobileMenu(){document.getElementById("sidebar")?.classList.add("open");document.getElementById("mobileBackdrop")?.classList.add("show");}
export function closeMobileMenu(){document.getElementById("sidebar")?.classList.remove("open");document.getElementById("mobileBackdrop")?.classList.remove("show");}
export function escapeHtml(value){return String(value||"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));}
export function escapeAttr(value){return escapeHtml(value).replace(/`/g,"&#96;");}
