import {
  call, canRead, canWrite, closeDialog, confirmAction, empty, errorPanel, escapeAttr,
  escapeHtml, fmtDate, isAdmin, loading, openDialog, optionList, runWrite, statusBadge
} from "./common.js";
import { phase3State } from "./state.js";

function target(){return document.getElementById("adminPanel");}
function setStatus(text,type="success"){const el=document.getElementById("adminStatus");if(el){el.textContent=text;el.className=`status-pill ${type}`;}}

export async function hydrateAdmin(){setStatus("Adminzugriff bestätigt","success");renderAdminHome();}
function action(id,icon,title,text){return `<button class="admin-action" type="button" data-admin-action="${escapeAttr(id)}"><strong>${icon} ${escapeHtml(title)}</strong><span>${escapeHtml(text)}</span></button>`;}
function renderAdminHome(){
  const fan=[];const portal=[];
  if(canWrite("Verwaltung")&&canWrite("Beiträge"))fan.push(action("season","📅","Neue Saison starten","Legt die Beiträge für eine neue Saison an."));
  if(canWrite("Verwaltung")&&canWrite("Kasse"))fan.push(action("yearclose","📊","Jahresabschluss","Erstellt die finanzielle Jahreszusammenfassung."));
  if(canWrite("Verwaltung"))fan.push(action("datacheck","✓","Datenprüfung","Prüft die fachliche Datenstruktur."));
  if(canRead("Benutzeranträge"))portal.push(action("requests","✉️","Freischaltungsanträge","Unbekannte Google-Konten prüfen und freigeben."));
  if(canRead("Rollen"))portal.push(action("users","🔐","Benutzer & Rollen","Benutzerkonten und Rollen verwalten."));
  if(canWrite("Verwaltung"))portal.push(action("backup","💾","Backup","Erstellt einen Snapshot aller aktiven DB_-Tabellen."));
  if(canRead("System"))portal.push(action("system","⚙️","Systemstatus","Zeigt Tabellenstatus und technische Hinweise."),action("audit","☷","Audit-Log","Zeigt nachvollziehbare Änderungen und Ereignisse."));
  if(isAdmin())portal.push(action("clean","🧹","Grundsystem herstellen","Sicherheitsgeschützte Bereinigung auf den definierten Produktivstand."));
  target().innerHTML=`<section><div class="section-title"><div><h3>Fanclubverwaltung</h3><p>Saison, Jahresabschluss und fachliche Prüfungen.</p></div></div><div class="admin-actions" style="margin-top:14px">${fan.join("")||empty("Keine Fanclub-Administrationsfunktionen freigegeben.")}</div></section><section><div class="section-title"><div><h3>Portalverwaltung</h3><p>Benutzer, Rechte, Sicherung und technischer Status.</p></div></div><div class="admin-actions" style="margin-top:14px">${portal.join("")||empty("Keine Portalverwaltungsfunktionen freigegeben.")}</div></section><article class="card"><h3>v3-Abgrenzung</h3><p>Bus-Modul und Push-Benachrichtigungen werden bewusst nicht in v3 umgesetzt. Die PWA-Struktur bleibt dafür in v4 erweiterbar.</p></article>`;
  document.querySelectorAll("[data-admin-action]").forEach(b=>b.addEventListener("click",()=>runAction(b.dataset.adminAction)));
}
async function runAction(id){try{if(id==="season")return seasonDialog();if(id==="yearclose")return yearCloseDialog();if(id==="datacheck")return runDataCheck();if(id==="requests")return openRequests();if(id==="users")return openUsers();if(id==="backup")return createBackup();if(id==="system")return openSystem();if(id==="audit")return openAudit();if(id==="clean")return openCleanSystem();}catch(error){target().innerHTML=errorPanel(error);}}
function seasonDialog(){openDialog({title:"Neue Saison starten",kicker:"Fanclubverwaltung",body:`<form><label>Saison/Jahr<input name="seasonName" value="${new Date().getFullYear()+1}" required></label><div class="notice warning" style="margin-top:14px">Für beitragspflichtige Mitglieder werden Beiträge angelegt. Bestehende Saisonwerte werden serverseitig geprüft.</div></form>`,onSubmit:async data=>{await runWrite("Neue Saison wird angelegt …",()=>call("apiStartNewSeason",data.seasonName));closeDialog();}});}
function yearCloseDialog(){openDialog({title:"Jahresabschluss",kicker:"Fanclubverwaltung",body:`<form><label>Jahr<input type="number" name="year" value="${new Date().getFullYear()}" required></label></form>`,onSubmit:async data=>{await runWrite("Jahresabschluss wird erstellt …",()=>call("apiCreateYearClose",Number(data.year)));closeDialog();}});}
async function runDataCheck(){const result=await runWrite("Datenprüfung läuft …",()=>call("apiRunDataCheck"),"Datenprüfung abgeschlossen.");openDialog({title:"Datenprüfung",kicker:`${Number(result.count||0)} Hinweis(e)`,wide:true,body:`${result.issues?.length?`<div class="settings-grid">${result.issues.map(issue=>`<div class="card"><strong>${escapeHtml(issue[0]||"Hinweis")} · ${escapeHtml(issue[1]||"")}</strong><p>${escapeHtml(issue[2]||"")}</p></div>`).join("")}</div>`:'<div class="notice success">Keine fachlichen Probleme gefunden.</div>'}<div class="dialog-actions"><button class="button ghost" data-dialog-close>Schließen</button></div>`});}

async function openUsers(force=false){let data=phase3State.get("admin:roles");if(!data||force)data=phase3State.set("admin:roles",await call("apiListRoles"));const users=data.roles||[];const roleNames=data.meta?.rollen||[];openDialog({title:"Benutzer & Rollen",kicker:`${users.length} Benutzer`,wide:true,body:`<div class="module-toolbar"><input id="adminUserSearch" class="grow" placeholder="Benutzer suchen …">${canWrite("Rollen")?'<button id="adminNewUser" class="button primary">+ Benutzer</button>':""}<button id="adminUsersRefresh" class="button ghost">Aktualisieren</button></div><div id="adminUserResults" style="margin-top:16px"></div><div class="dialog-actions"><button class="button ghost" data-dialog-close>Schließen</button></div>`});const render=()=>{const q=String(document.getElementById("adminUserSearch")?.value||"").toLowerCase();const list=users.filter(u=>!q||[u.id,u.name,u.email,u.rolle,u.mitgliedsId].join(" ").toLowerCase().includes(q));document.getElementById("adminUserResults").innerHTML=list.length?`<div class="card table-card"><div class="data-table-wrap"><table class="data-table"><thead><tr><th>Benutzer</th><th>Rolle</th><th>Google</th><th>Status</th><th></th></tr></thead><tbody>${list.map(u=>`<tr><td><strong>${escapeHtml(u.name||u.email||u.id)}</strong><div class="subtle">${escapeHtml(u.id)}${u.mitgliedsId?` · ${escapeHtml(u.mitgliedsId)}`:""}</div></td><td>${escapeHtml(u.rolle)}</td><td>${u.googleVerknuepft?'<span class="badge success">Verbunden</span>':'<span class="badge neutral">Nicht verbunden</span>'}</td><td>${statusBadge(u.aktiv)}</td><td>${canWrite("Rollen")?`<div class="button-row"><button class="button small ghost" data-user-edit="${escapeAttr(u.id)}">Bearbeiten</button><button class="button small ${u.aktiv==="JA"?"danger":"secondary"}" data-user-toggle="${escapeAttr(u.id)}" data-active="${u.aktiv==="JA"?"false":"true"}">${u.aktiv==="JA"?"Deaktivieren":"Aktivieren"}</button>${u.googleVerknuepft?`<button class="button small ghost" data-user-unlink="${escapeAttr(u.id)}">Google lösen</button>`:""}</div>`:""}</td></tr>`).join("")}</tbody></table></div></div>`:empty("Keine Benutzer gefunden.");document.querySelectorAll("[data-user-edit]").forEach(b=>b.addEventListener("click",()=>openUserForm(users.find(u=>u.id===b.dataset.userEdit),roleNames)));document.querySelectorAll("[data-user-toggle]").forEach(b=>b.addEventListener("click",()=>toggleUser(b.dataset.userToggle,b.dataset.active==="true")));document.querySelectorAll("[data-user-unlink]").forEach(b=>b.addEventListener("click",()=>unlinkUser(b.dataset.userUnlink)));};render();document.getElementById("adminUserSearch")?.addEventListener("input",render);document.getElementById("adminNewUser")?.addEventListener("click",()=>openUserForm({},roleNames));document.getElementById("adminUsersRefresh")?.addEventListener("click",()=>{closeDialog();phase3State.remove("admin:roles");openUsers(true);});}
function openUserForm(user={},roles=[]){openDialog({title:user.id?"Benutzer bearbeiten":"Benutzer anlegen",kicker:user.id||"Neues Benutzerkonto",body:`<form><input type="hidden" name="id" value="${escapeAttr(user.id||"")}"><div class="form-grid"><label>Vorname<input name="vorname" value="${escapeAttr(user.vorname||"")}"></label><label>Nachname<input name="nachname" value="${escapeAttr(user.nachname||"")}"></label><label class="full">Anzeigename<input name="name" value="${escapeAttr(user.name||"")}"></label><label>Google-E-Mail<input type="email" name="email" value="${escapeAttr(user.email||"")}"></label><label>Mitglieds-ID<input name="mitgliedsId" value="${escapeAttr(user.mitgliedsId||"")}" placeholder="optional"></label><label>Rolle<select name="rolle">${optionList(roles,user.rolle||roles[0],"Rolle auswählen")}</select></label><label>Aktiv<select name="aktiv">${optionList(["JA","NEIN"],user.aktiv||"JA")}</select></label><label class="full">Telefon<input name="telefon" value="${escapeAttr(user.telefon||"")}"></label><label class="full">Bemerkung<textarea name="bemerkung">${escapeHtml(user.bemerkung||"")}</textarea></label></div></form>`,onSubmit:async data=>{await runWrite("Benutzer wird gespeichert …",()=>call("apiSaveRole",data));closeDialog();phase3State.remove("admin:roles");openUsers(true);}});}
async function toggleUser(id,active){await runWrite(active?"Benutzer wird aktiviert …":"Benutzer wird deaktiviert …",()=>call("apiSetRoleActive",id,active));closeDialog();phase3State.remove("admin:roles");openUsers(true);}
async function unlinkUser(id){if(!await confirmAction({title:"Google-Verknüpfung lösen",message:"Der Benutzer muss sich danach erneut mit dem hinterlegten Google-Konto verbinden.",confirmText:"Verknüpfung lösen"}))return;await runWrite("Google-Verknüpfung wird gelöst …",()=>call("apiResetGoogleLink",id));closeDialog();phase3State.remove("admin:roles");openUsers(true);}

async function openRequests(){const data=await call("apiListAccessRequests",{status:"alle"});const rows=data.requests||[];openDialog({title:"Freischaltungsanträge",kicker:`${rows.length} Antrag/Anträge`,wide:true,body:rows.length?`<div class="settings-grid">${rows.map(r=>`<article class="card"><div class="entity-head"><div><h3>${escapeHtml(r.name||r.email||r.id)}</h3><span class="subtle">${escapeHtml(r.email||"")} · ${escapeHtml(fmtDate(r.antragAm))}</span></div>${statusBadge(r.status)}</div><div class="button-row" style="margin-top:14px">${canWrite("Benutzeranträge")&&String(r.status).toLowerCase()==="offen"?`<button class="button small primary" data-request-approve="${escapeAttr(r.id)}">Freigeben</button><button class="button small danger" data-request-reject="${escapeAttr(r.id)}">Ablehnen</button>`:""}</div></article>`).join("")}</div>`:empty("Keine Freischaltungsanträge vorhanden.")});document.querySelectorAll("[data-request-approve]").forEach(b=>b.addEventListener("click",()=>approveRequest(rows.find(r=>r.id===b.dataset.requestApprove),data.meta||{})));document.querySelectorAll("[data-request-reject]").forEach(b=>b.addEventListener("click",()=>rejectRequest(b.dataset.requestReject)));}
function approveRequest(request,meta){openDialog({title:"Benutzer freigeben",kicker:request.email||request.id,body:`<form><input type="hidden" name="antragId" value="${escapeAttr(request.id)}"><div class="form-grid"><label>Rolle<select name="rolle">${optionList(meta.roles||[],"","Rolle auswählen")}</select></label><label>Mitglieds-ID<select name="mitgliedsId">${optionList(meta.members||[],"","Keine Verknüpfung")}</select></label><label class="full">Bemerkung<textarea name="bemerkung"></textarea></label></div></form>`,onSubmit:async data=>{await runWrite("Antrag wird freigegeben …",()=>call("apiApproveAccessRequest",data));closeDialog();openRequests();}});}
async function rejectRequest(id){if(!await confirmAction({title:"Antrag ablehnen",message:"Der Freischaltungsantrag wird abgelehnt.",confirmText:"Ablehnen"}))return;await runWrite("Antrag wird abgelehnt …",()=>call("apiRejectAccessRequest",{antragId:id,bemerkung:"Über PWA abgelehnt"}));closeDialog();openRequests();}

async function createBackup(){const result=await runWrite("Backup wird erstellt …",()=>call("apiCreateBackup"),"Backup wurde erstellt.");openDialog({title:"Backup abgeschlossen",kicker:"Portalverwaltung",body:`<div class="notice success">${escapeHtml(result.message||"Backup wurde erstellt.")}</div><div class="dialog-actions"><button class="button ghost" data-dialog-close>Schließen</button></div>`});}
async function openSystem(){const data=await call("apiGetSystemStatus");openDialog({title:"Systemstatus",kicker:data.message||"DB_-Status",wide:true,body:`${data.warnings?.length?`<div class="notice warning">${data.warnings.map(escapeHtml).join("<br>")}</div>`:'<div class="notice success">Keine technischen Warnungen.</div>'}<div class="card table-card" style="margin-top:16px"><div class="data-table-wrap"><table class="data-table"><thead><tr><th>Tabelle</th><th>Status</th><th>Datenzeilen</th><th>Physische Zeilen</th></tr></thead><tbody>${(data.sheets||[]).map(s=>`<tr><td>${escapeHtml(s.name)}</td><td>${statusBadge(s.status)}</td><td>${Number(s.effectiveRows||0)}</td><td>${Number(s.physicalRows||0)}</td></tr>`).join("")}</tbody></table></div></div><div class="dialog-actions"><button class="button ghost" data-dialog-close>Schließen</button></div>`});}
async function openAudit(){const data=await call("apiListAuditLog",{max:200});const rows=data.entries||data.logs||data.items||[];openDialog({title:"Audit-Log",kicker:`${rows.length} Einträge`,wide:true,body:rows.length?`<div class="card table-card"><div class="data-table-wrap"><table class="data-table"><thead><tr><th>Zeit</th><th>Aktion</th><th>Bereich</th><th>Benutzer</th><th>Details</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${escapeHtml(r.zeitpunkt||r.timestamp||"")}</td><td>${escapeHtml(r.aktion||r.action||"")}</td><td>${escapeHtml(r.bereich||r.area||"")}</td><td>${escapeHtml(r.benutzer||r.user||"")}</td><td>${escapeHtml(r.bemerkung||r.details||"")}</td></tr>`).join("")}</tbody></table></div></div>`:empty("Noch keine Audit-Einträge vorhanden.")});}
async function openCleanSystem(){const preview=await call("apiGetCleanSystemPreview");openDialog({title:"Grundsystem herstellen",kicker:preview.ready?"Bereit":"Sicherheitsabbruch",wide:true,body:`<div class="notice ${preview.ready?"warning":"error"}">${escapeHtml(preview.message||"")}</div><div class="grid three" style="margin-top:16px"><article class="card"><h3>Erhaltene Google-Benutzer</h3><strong>${Number(preview.googleLinkedCount||preview.linkedUsers?.length||0)}</strong></article><article class="card"><h3>Zielrollen</h3><strong>${Number(preview.targetRoles?.length||7)}</strong></article><article class="card"><h3>Konten / Teams</h3><strong>5 / 3</strong></article></div>${preview.ready?`<form id="cleanSystemForm" style="margin-top:16px"><label>Bestätigungstext<input name="confirmation" autocomplete="off" placeholder="GRUNDSYSTEM HERSTELLEN" required></label><label class="check-row" style="margin-top:14px"><input type="checkbox" name="secondConfirmation"> Automatisches Backup und endgültige Bereinigung bestätigen</label><div class="dialog-actions"><button class="button ghost" data-dialog-close type="button">Abbrechen</button><button class="button danger" type="submit">Grundsystem herstellen</button></div></form>`:'<div class="dialog-actions"><button class="button ghost" data-dialog-close>Schließen</button></div>'}`});const form=document.getElementById("cleanSystemForm");form?.addEventListener("submit",async event=>{event.preventDefault();const confirmation=form.elements.confirmation.value;const secondConfirmation=form.elements.secondConfirmation.checked;if(confirmation!=="GRUNDSYSTEM HERSTELLEN"||!secondConfirmation){throw new Error("Bestätigung ist unvollständig.");}if(!await confirmAction({title:"Letzte Sicherheitsabfrage",message:"Alle Bewegungs- und Testdaten werden nach einem Backup gelöscht.",confirmText:"Endgültig ausführen",phrase:"JETZT BEREINIGEN"}))return;await runWrite("Grundsystem wird hergestellt …",()=>call("apiResetToCleanSystem",{confirmation,secondConfirmation}));closeDialog();location.reload();});}
