import {
  call,
  errorPanel,
  escapeAttr,
  escapeHtml,
  loading,
  openDialog,
  optionList,
  runWrite,
  showToast
} from "./common.js";

let snapshot = null;
let archiveSnapshot = null;
let currentTeamId = "";
let currentArchiveEventId = "";
let currentView = "teams";

const POSITION_LABELS = Object.freeze({ GOALIE: "Tor", DEFENSE: "Verteidigung", FORWARD: "Sturm" });

function ensureLivetickerAdminStyles() {
  if (document.querySelector("style[data-liveticker-admin-styles]")) return;
  const style = document.createElement("style");
  style.dataset.livetickerAdminStyles = "true";
  style.textContent = `
    .v4-dialog .liveticker-admin-form{display:grid!important;grid-template-columns:minmax(0,1fr)!important;gap:14px!important;width:100%!important;margin:0!important}
    .v4-dialog .liveticker-admin-form>label{grid-column:1/-1!important;min-width:0!important;width:100%!important;max-width:none!important;contain:none!important}
    .v4-dialog .liveticker-admin-form>label:not(.checkbox-row){display:grid!important;gap:6px!important;font-size:.82rem!important;font-weight:850!important;line-height:1.2!important}
    .v4-dialog .liveticker-admin-form input:not([type="checkbox"]),.v4-dialog .liveticker-admin-form select{width:100%!important;min-width:0!important;min-height:48px!important;padding:11px 12px!important;border:1px solid #aebdcd!important;border-radius:13px!important;background:#fff!important}
    .v4-dialog .liveticker-admin-form .checkbox-row{display:grid!important;grid-template-columns:32px minmax(0,1fr)!important;align-items:center!important;gap:12px!important;min-height:46px!important;padding:2px 0!important;font-size:.84rem!important;font-weight:850!important;line-height:1.25!important;cursor:pointer}
    .v4-dialog .liveticker-admin-form .checkbox-row>input[type="checkbox"]{appearance:auto!important;-webkit-appearance:checkbox!important;width:24px!important;height:24px!important;min-width:24px!important;min-height:24px!important;max-width:24px!important;margin:0!important;padding:0!important;justify-self:start!important;accent-color:#176fce}
    .liveticker-archive-score-card{display:grid;justify-items:center;gap:5px;padding:18px 14px;margin-bottom:14px;border:1px solid #d7e2ee;border-radius:16px;background:#f7faff;text-align:center}
    .liveticker-archive-score-card strong{font-size:2rem;line-height:1;letter-spacing:-.04em}.liveticker-archive-score-card small{color:#60748a;font-weight:800}
    .liveticker-archive-facts{display:grid;gap:0;margin-bottom:14px;border:1px solid #d7e2ee;border-radius:14px;overflow:hidden}.liveticker-archive-fact{display:flex;justify-content:space-between;gap:14px;padding:10px 12px;background:#fff;border-bottom:1px solid #e3eaf2;font-size:.82rem}.liveticker-archive-fact:last-child{border-bottom:0}.liveticker-archive-fact span{color:#60748a}.liveticker-archive-fact strong{text-align:right}
    @media(max-width:430px){.v4-dialog .liveticker-admin-form{gap:12px!important}.v4-dialog .liveticker-admin-form input:not([type="checkbox"]),.v4-dialog .liveticker-admin-form select{min-height:50px!important}.v4-dialog .liveticker-admin-form .checkbox-row{min-height:48px!important}}
  `;
  document.head.appendChild(style);
}

function normalizeCheckbox(values, name) { return { ...values, [name]: values[name] === "on" }; }
function teamForm(team = {}) { return `<form class="liveticker-admin-form"><input type="hidden" name="id" value="${escapeAttr(team.id || "")}"><label>Teamname<input name="name" required maxlength="160" placeholder="z. B. Mighty Dogs Schweinfurt" value="${escapeAttr(team.name || "")}"></label><label>Kurzname<input name="shortName" required maxlength="60" placeholder="z. B. Mighty Dogs" value="${escapeAttr(team.shortName || "")}"></label><label>Logo-URL<input name="logoUrl" type="url" inputmode="url" placeholder="https://…" value="${escapeAttr(team.logoUrl || "")}"></label><label class="checkbox-row"><input name="homeClub" type="checkbox" ${team.homeClub ? "checked" : ""}><span>Unser Verein / Heimverein</span></label><label class="checkbox-row"><input name="active" type="checkbox" ${team.active !== false ? "checked" : ""}><span>Team ist aktiv</span></label></form>`; }
function playerForm(team, player = {}) { return `<form class="liveticker-admin-form"><input type="hidden" name="id" value="${escapeAttr(player.id || "")}"><input type="hidden" name="teamId" value="${escapeAttr(team.id)}"><label>Trikotnummer<input name="number" maxlength="8" inputmode="numeric" placeholder="z. B. 84" value="${escapeAttr(player.number || "")}"></label><label>Position<select name="position" required>${optionList([{value:"GOALIE",label:"Tor"},{value:"DEFENSE",label:"Verteidigung"},{value:"FORWARD",label:"Sturm"}], player.position || "FORWARD")}</select></label><label>Name<input name="name" required maxlength="160" placeholder="Vorname Nachname" value="${escapeAttr(player.name || "")}"></label><label class="checkbox-row"><input name="active" type="checkbox" ${player.active !== false ? "checked" : ""}><span>Spieler ist aktiv</span></label></form>`; }

function openTeam(team = null) { openDialog({ title: team ? "Team bearbeiten" : "Team anlegen", kicker:"Liveticker · Teams", body:teamForm(team||{}), onSubmit:async values=>{ let payload=normalizeCheckbox(values,"homeClub"); payload=normalizeCheckbox(payload,"active"); if(team) payload.expectedRevision=team.revision; snapshot=await runWrite(()=>call("liveticker_team_save",payload),team?"Team wurde aktualisiert.":"Team wurde angelegt."); currentTeamId=payload.id||snapshot?.teams?.find(item=>item.name===payload.name)?.id||currentTeamId; render(); } }); }
function openPlayer(team, player = null) { openDialog({ title:player?"Spieler bearbeiten":"Spieler hinzufügen", kicker:team.shortName||team.name, body:playerForm(team,player||{}), onSubmit:async values=>{ const payload=normalizeCheckbox(values,"active"); if(player) payload.expectedRevision=player.revision; snapshot=await runWrite(()=>call("liveticker_player_save",payload),player?"Spieler wurde aktualisiert.":"Spieler wurde hinzugefügt."); currentTeamId=team.id; render(); } }); }
function playerRow(team, player) { const number=player.number?`#${escapeHtml(player.number)}`:"–"; return `<button class="v4-team-member-row is-actionable" type="button" data-player-id="${escapeAttr(player.id)}"><span class="v4-team-member-copy"><strong>${number} ${escapeHtml(player.name)}</strong><small>${escapeHtml(POSITION_LABELS[player.position]||player.position)}${player.active?"":" · inaktiv"}</small></span><span class="v4-row-chevron" aria-hidden="true">›</span></button>`; }
function groupPlayers(team,position){const players=(team.players||[]).filter(player=>player.position===position);if(!players.length)return"";return `<section class="v4-team-detail-section"><h3>${escapeHtml(POSITION_LABELS[position])}</h3><div class="v4-team-member-list">${players.map(player=>playerRow(team,player)).join("")}</div></section>`;}
function teamListRow(team){const activePlayers=(team.players||[]).filter(player=>player.active).length;return `<button class="v4-team-list-row" type="button" data-team-id="${escapeAttr(team.id)}"><span><strong>${escapeHtml(team.shortName||team.name)}${team.homeClub?" · 🏠":""}</strong><small>${activePlayers} aktive Spieler${team.active?"":" · Team inaktiv"}</small></span><span class="v4-row-chevron" aria-hidden="true">›</span></button>`;}
function teamDetail(team){return `<div class="v4-team-detail"><div class="v4-section-heading"><div><span class="subtle">Teamverwaltung</span><h2>Kader</h2></div><div class="button-row"><button class="button small secondary" type="button" data-edit-team>Team bearbeiten</button><button class="button small primary" type="button" data-add-player>+ Spieler</button></div></div>${team.logoUrl?`<p class="subtle">Logo: ${escapeHtml(team.logoUrl)}</p>`:""}${groupPlayers(team,"GOALIE")}${groupPlayers(team,"DEFENSE")}${groupPlayers(team,"FORWARD")}${(team.players||[]).length?"":'<div class="notice neutral">Noch keine Spieler angelegt.</div>'}</div>`;}
function bindTeamDetail(panel,team){panel.querySelector("[data-edit-team]")?.addEventListener("click",()=>openTeam(team));panel.querySelector("[data-add-player]")?.addEventListener("click",()=>openPlayer(team));panel.querySelectorAll("[data-player-id]").forEach(button=>button.addEventListener("click",()=>{const player=(team.players||[]).find(item=>item.id===button.dataset.playerId);if(player)openPlayer(team,player);}));}
function archiveDate(value){if(!value)return"–";const date=new Date(`${value}T12:00:00`);return Number.isNaN(date.getTime())?String(value):new Intl.DateTimeFormat("de-DE",{day:"2-digit",month:"2-digit",year:"numeric"}).format(date);}
function archiveCompletedAt(value){if(!value)return"–";const date=new Date(value);return Number.isNaN(date.getTime())?String(value):new Intl.DateTimeFormat("de-DE",{dateStyle:"short",timeStyle:"short"}).format(date);}
function archiveScore(game){const own=Number(game.ownScore||0),opponent=Number(game.opponentScore||0);return game.homeAway==="AWAY"?`${opponent}:${own}`:`${own}:${opponent}`;}
function archiveScoreLabel(game){const suffix=String(game.suffix||"").trim();return `${archiveScore(game)}${suffix?` ${suffix}`:""}`;}
function archiveRow(game){return `<button class="v4-team-list-row" type="button" data-archive-event-id="${escapeAttr(game.eventId)}"><span><strong>${escapeHtml(game.displayTitle||"Spiel")}</strong><small>${escapeHtml(archiveDate(game.eventDate))} · Endstand ${escapeHtml(archiveScoreLabel(game))}</small></span><span class="v4-row-chevron" aria-hidden="true">›</span></button>`;}
function archiveDetail(game){const venue=String(game.venue||"").trim()||"–";return `<div class="liveticker-archive-detail"><div class="liveticker-archive-score-card"><span class="subtle">Endstand</span><strong>${escapeHtml(archiveScoreLabel(game))}</strong><small>${escapeHtml(game.displayTitle||"Spiel")}</small></div><div class="liveticker-archive-facts"><div class="liveticker-archive-fact"><span>Spieltag</span><strong>${escapeHtml(archiveDate(game.eventDate))}</strong></div><div class="liveticker-archive-fact"><span>Abgeschlossen</span><strong>${escapeHtml(archiveCompletedAt(game.completedAt))}</strong></div><div class="liveticker-archive-fact"><span>Letzte Spielminute</span><strong>${escapeHtml(game.minute||1)}</strong></div><div class="liveticker-archive-fact"><span>Tore erfasst</span><strong>${escapeHtml(game.goalCount||0)}</strong></div><div class="liveticker-archive-fact"><span>Strafen erfasst</span><strong>${escapeHtml(game.penaltyCount||0)}</strong></div><div class="liveticker-archive-fact"><span>Spielort</span><strong>${escapeHtml(venue)}</strong></div></div><div class="button-row"><button class="button danger" type="button" data-reset-archive-game>Spiel zurücksetzen</button></div></div>`;}
function confirmArchiveReset(game){openDialog({title:"Spiel zurücksetzen?",kicker:game.displayTitle||"Liveticker · Archiv",body:`<div class="notice warning"><strong>Der gespeicherte Spielstand wird geleert.</strong><p>Tore, Strafen, Penaltyschießen und Spielminute werden zurückgesetzt. Das Kalenderspiel selbst bleibt bestehen und kann danach erneut getickert werden.</p></div>`,submitLabel:"Spiel zurücksetzen",danger:true,onSubmit:async()=>{archiveSnapshot=await runWrite(()=>call("liveticker_game_reset",{eventId:game.eventId,expectedRevision:game.revision}),"Spiel wurde zurückgesetzt.");currentArchiveEventId="";render();}});}
async function showArchive(){currentView="archive";currentTeamId="";currentArchiveEventId="";archiveSnapshot=null;render();try{archiveSnapshot=await call("liveticker_archive_list");render();}catch(error){const panel=document.getElementById("livetickerRosterPanel");if(panel)panel.innerHTML=errorPanel(error,"Spielarchiv konnte nicht geladen werden");showToast(error?.message||"Spielarchiv konnte nicht geladen werden.","error",6500);}}
function renderArchive(toolbar,panel){const games=archiveSnapshot?.games||[];const currentGame=currentArchiveEventId?games.find(game=>game.eventId===currentArchiveEventId)||null:null;if(currentArchiveEventId&&!currentGame)currentArchiveEventId="";if(currentGame){toolbar.innerHTML=`<div class="v4-section-heading"><div><span class="subtle">Liveticker · Archiv</span><h2>${escapeHtml(currentGame.displayTitle||"Spiel")}</h2><p class="subtle">Abgeschlossenes Spiel ansehen oder zurücksetzen.</p></div><button class="button small secondary" type="button" data-back-archive>← Archiv</button></div>`;panel.innerHTML=archiveDetail(currentGame);toolbar.querySelector("[data-back-archive]")?.addEventListener("click",()=>{currentArchiveEventId="";render();});panel.querySelector("[data-reset-archive-game]")?.addEventListener("click",()=>confirmArchiveReset(currentGame));return;}toolbar.innerHTML=`<div class="v4-section-heading"><div><span class="subtle">Liveticker</span><h2>Spielarchiv</h2><p class="subtle">Abgeschlossene Liveticker-Spiele.</p></div><button class="button small secondary" type="button" data-back-teams>← Teams</button></div>`;panel.innerHTML=!archiveSnapshot?loading("Spielarchiv wird geladen …"):games.length?`<div class="v4-team-list">${games.map(archiveRow).join("")}</div>`:'<div class="notice neutral">Noch keine abgeschlossenen Spiele im Liveticker-Archiv.</div>';toolbar.querySelector("[data-back-teams]")?.addEventListener("click",()=>{currentView="teams";currentArchiveEventId="";render();});panel.querySelectorAll("[data-archive-event-id]").forEach(button=>button.addEventListener("click",()=>{currentArchiveEventId=button.dataset.archiveEventId||"";render();}));}
function render(){const toolbar=document.getElementById("livetickerRosterToolbar"),panel=document.getElementById("livetickerRosterPanel");if(!toolbar||!panel)return;if(currentView==="archive"){renderArchive(toolbar,panel);return;}const teams=snapshot?.teams||[];const currentTeam=currentTeamId?teams.find(team=>team.id===currentTeamId)||null:null;if(currentTeamId&&!currentTeam)currentTeamId="";if(currentTeam){toolbar.innerHTML=`<div class="v4-section-heading"><div><span class="subtle">Liveticker · Teams & Kader</span><h2>${escapeHtml(currentTeam.name)}</h2><p class="subtle">Mannschaft und Kader bearbeiten.</p></div><button class="button small secondary" type="button" data-back-teams>← Zurück</button></div>`;panel.innerHTML=teamDetail(currentTeam);toolbar.querySelector("[data-back-teams]")?.addEventListener("click",()=>{currentTeamId="";render();});bindTeamDetail(panel,currentTeam);return;}toolbar.innerHTML=`<div class="v4-section-heading"><div><span class="subtle">Liveticker</span><h2>Teams & Kader</h2><p class="subtle">Team auswählen oder neu anlegen.</p></div><div class="button-row"><a class="button small secondary" href="./liveticker/">Ticker öffnen</a><button class="button small secondary" type="button" data-open-archive>Archiv</button><button class="button small primary" type="button" data-add-team>+ Team</button></div></div>`;panel.innerHTML=teams.length?`<div class="v4-team-list">${teams.map(teamListRow).join("")}</div>`:'<div class="notice neutral">Noch keine Liveticker-Teams angelegt.</div>';toolbar.querySelector("[data-open-archive]")?.addEventListener("click",()=>showArchive());toolbar.querySelector("[data-add-team]")?.addEventListener("click",()=>openTeam());panel.querySelectorAll("[data-team-id]").forEach(button=>button.addEventListener("click",()=>{currentTeamId=button.dataset.teamId||"";render();}));}
export async function hydrateLivetickerAdmin(context={}){ensureLivetickerAdminStyles();currentView="teams";currentTeamId="";currentArchiveEventId="";archiveSnapshot=null;const panel=document.getElementById("livetickerRosterPanel");if(panel)panel.innerHTML=loading("Teams und Kader werden geladen …");try{snapshot=await call("liveticker_teams_list");if(context.isCurrent&&!context.isCurrent())return;render();}catch(error){if(context.isCurrent&&!context.isCurrent())return;if(panel)panel.innerHTML=errorPanel(error,"Liveticker-Teams konnten nicht geladen werden");showToast(error?.message||"Liveticker-Teams konnten nicht geladen werden.","error",6500);}}
export function noop() {}
